<div id="holderData">
        <?=$this->formRow($this->holderForm->get('creditCardHolderName'));?>
        <?=$this->formRow($this->holderForm->get('creditCardHolderCPF'));?>
        <?=$this->formRow($this->holderForm->get('creditCardHolderAreaCode'));?>
        <?=$this->formRow($this->holderForm->get('creditCardHolderPhone'));?>
        <?=$this->formRow($this->holderForm->get('billingAddressPostalCode'));?>
        <?=$this->formRow($this->holderForm->get('billingAddressStreet'));?>
        <?=$this->formRow($this->holderForm->get('billingAddressNumber'));?>
        <?=$this->formRow($this->holderForm->get('billingAddressComplement'));?>
        <?=$this->formRow($this->holderForm->get('billingAddressDistrict'));?>
        <?=$this->formRow($this->holderForm->get('billingAddressCity'));?>
        <?=$this->formRow($this->holderForm->get('billingAddressState'));?>
        <?=$this->formRow($this->holderForm->get('billingAddressCountry'));?>
</div>