<div  id="buyerData">
    <?=$this->formRow($this->form->get('senderEmail'));?>
    <?=$this->formRow($this->form->get('senderName'));?>
    <?=$this->formRow($this->form->get('senderCPF'));?>
    <?=$this->formRow($this->form->get('senderAreaCode'));?>
    <?=$this->formRow($this->form->get('senderPhone'));?>
    <?=$this->formRow($this->form->get('shippingAddressPostalCode'));?>
    <?=$this->formRow($this->form->get('shippingAddressStreet'));?>
    <?=$this->formRow($this->form->get('shippingAddressNumber'));?>
    <?=$this->formRow($this->form->get('shippingAddressDistrict'));?>
    <?=$this->formRow($this->form->get('shippingAddressComplement'));?>
    <?=$this->formRow($this->form->get('shippingAddressCity'));?>
    <?=$this->formRow($this->form->get('shippingAddressState'));?>
    <?=$this->formRow($this->form->get('shippingAddressCountry'));?>
</div>
