<div class="row">
    <div class="co-md-6 col-xs-12">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a class="changePaymentMethod" href="#creditCard" aria-controls="creditCard" role="tab" data-toggle="tab">Pagar com cartão</a></li>
            <li role="presentation"><a class="changePaymentMethod" href="#boleto" aria-controls="boleto" role="tab" data-toggle="tab">Pagar com boleto</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="creditCard">
                <?php echo $this->partial('./templates/paymentMethods.inc.phtml');?>
            </div>
            <div role="tabpanel" class="tab-pane" id="boleto">
                <div id="mensagem-boleto"></div>
                <h2>Pagar com Boleto</h2>
                <p>Clique no botão abaixo para gerar o boleto e fazer o pagamento da conta</p>
                <?php echo $this->partial('./templates/boletoData.inc.phtml');?>
            </div>
        </div>
        <?php echo $this->partial('./templates/buyerData.inc.phtml');?>
        <?php echo $this->partial('./templates/orderData.inc.phtml');?>


    </div>
</div>